[package]
name = "dfm"
description = "A dotfile manager for lazy people and pair programmers."
license = "Apache-2.0"
license-file = "LICENSE"
version = "10.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive", "cargo"] }
clap_complete = "4.2.1"
lazy_static = "1.4.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
shellexpand = "3.1.0"
shlex = "1.1.0"
text_io = "0.1.12"
walkdir = "2.3.3"
